### PR TITLE
Eliminated dependence on jQuery

### PR DESCRIPTION
**Pull request by koceg**
We really don't need jQuery for such a simple task.

### CODE REVIEW

**Comment by koceg** [comment]
There is no need to wrap our code in `ready` now too, because we don't work with DOM and have no dependencies.
But we do need a closure, however, to avoid pollution of global scope and conflicts in variable names.

**Comment by SpareJobs** [comment]
@koceg makes a very good point. Also for developers who use Angular with Laravel, throwing jQuery into the mix can be messy.

**Comment by olimorris** [comment]
@koceg makes a very good point. Also for developers who use Angular with Laravel, throwing jQuery into the mix can be messy.

**Comment by mikebronner** [comment]
Completely agree with all your points! :) @koceg thanks for making a PR.

**Pull request merged**
