### PR TITLE
Update dependencies for Laravel 10

### PR DESCRIPTION
**Pull request by DariusIII**

### CODE REVIEW

**Comment by mikebronner** [comment]
@DariusIII  Marking this as WIP until the dependencies can be met. Please also update `travis.yml` for the new PHP requirements to test against 8.1 and 8.2. Once `composer update` works feel free to mark this PR as ready for review. Thanks for submitting this, unfortunately one of the dependencies is notoriously slow to update.

**Comment by mikebronner** [comment]
> I have commented here: #145 Anyway, i am using my fork with no issues for now, at least none that i noticed.

Nice, thanks for the update :)

**Comment by mikebronner** [comment]
I'm going to merge and sort out jenssegers/model, then release under a new version

**Comment by carestad** [comment]
I am trying to upgrade to v10, but I am seeing all sorts of errors. I suspect it could be due to `minimum-stability: "dev"` in `composer.json` here. The upgrade guide for Laravel 10 states that applications should change this to `"stable"` now. Could that be the case?

**Comment by mikebronner** [comment]
@carestad Please provide the output from trying to run `composer update`.

**Comment by DariusIII** [comment]
> I am trying to upgrade to v10, but I am seeing all sorts of errors. I suspect it could be due to `minimum-stability: "dev"` in `composer.json` here. [The upgrade guide for Laravel 10](https://laravel.com/docs/10.x/upgrade#updating-minimum-stability) states that applications should change this to `"stable"` now. Could that be the case?

What is minimum stability in composer.json you use? I am using this package without any issue, and minimum stability on my project is still dev.

**Comment by carestad** [comment]
> @carestad Please provide the output from trying to run `composer update`.

Hi! Sorry, forgot to include that part :sweat_smile: here we go:

```
./composer.json has been updated
Running composer update genealabs/laravel-caffeine
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - genealabs/laravel-caffeine[0.1.0, ..., 0.3.12] require illuminate/support ~5.1 -> found illuminate/support[v5.1.1, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.4.0, ..., 0.4.1] require illuminate/support 5.1.* || 5.3.* -> found illuminate/support[v5.1.1, ..., v5.3.23] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 0.4.2 requires illuminate/support 5.1.* || 5.3.* || 5.4.* -> found illuminate/support[v5.1.1, ..., v5.4.36] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 0.5.0 requires illuminate/support 5.1.* || 5.3.* || 5.4.* || 5.5.* -> found illuminate/support[v5.1.1, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.6.4, ..., 0.6.5] require illuminate/support 5.0 - 5.5 -> found illuminate/support[v5.0.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.6.0, ..., 0.6.6] require illuminate/routing 5.5.* -> found illuminate/routing[v5.5.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 0.6.7 requires illuminate/routing 5.6.* -> found illuminate/routing[v5.6.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.6.8, ..., 0.6.12] require illuminate/routing 5.3 - 5.6 -> found illuminate/routing[v5.3.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.7.0, ..., 0.7.1] require illuminate/routing 5.3 - 5.7 -> found illuminate/routing[v5.3.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.8.0, ..., 0.8.3] require illuminate/routing 5.3 - 5.8 -> found illuminate/routing[v5.3.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 1.0.0 requires illuminate/routing 6.0 -> found illuminate/routing[v6.0.0] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[1.0.1, ..., 1.0.5] require illuminate/routing ^6.0 -> found illuminate/routing[v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[7.0.0, ..., 7.0.2] require illuminate/routing ^7.0 -> found illuminate/routing[v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[9.0.0, ..., 9.0.4] require illuminate/routing ^9.0 -> found illuminate/routing[v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[8.0.0, 9.0.1] require illuminate/routing ^8.0 -> found illuminate/routing[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 10.0.0 requires jenssegers/model dev-master@dev -> found jenssegers/model[dev-master] but it does not match your minimum-stability.
    - Root composer.json requires genealabs/laravel-caffeine * -> satisfiable by genealabs/laravel-caffeine[0.1.0, ..., 0.8.3, 1.0.0, ..., 1.0.5, 7.0.0, 7.0.1, 7.0.2, 8.0.0, 9.0.0, ..., 9.0.4, 10.0.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require genealabs/laravel-caffeine:*" to figure out if any version is installable, or "composer require genealabs/laravel-caffeine:^2.1" if you know which you need.
```

Also if I specify the version when trying to require it with `composer req genealabs/laravel-caffeine:^10` I get:

```
./composer.json has been updated
Running composer update genealabs/laravel-caffeine
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jenssegers/model dev-master requires illuminate/contracts ^5.0|^6.0|^7.0|^8.0|^9.0 -> found illuminate/contracts[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 10.0.0 requires jenssegers/model dev-master@dev -> satisfiable by jenssegers/model[dev-master].
    - Root composer.json requires genealabs/laravel-caffeine ^10 -> satisfiable by genealabs/laravel-caffeine[10.0.0].


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

---

> What is minimum stability in composer.json you use? I am using this package without any issue, and minimum stability on my project is still dev. Although i do have `"prefer-stable": true,` And this project has this also, so i believe your issue is with something else.

Currently my `minimum-stability` is set to `stable`, as per the upgrade guide. I can try and do some more testing around that.

I had some similar issues with some local Laravel Nova components that I had, and I had to set a specific `version` in their `composer.json` files, otherwise it would just assume their versions to be `dev-<branch name>` which in turn did not make composer happy.

Maybe it could be related to https://github.com/Kyzegs/model/blob/main/composer.json not having a `minimum-stability` at all though? I am not 100% sure where the problem lies quite yet :sweat_smile:

**Comment by carestad** [comment]
I can also add that this also happens with a newly created Laravel application, created with `laravel new test` (for example), and then cd'ing into that directory and running `composer require genealabs/laravel-caffeine`.

Output from that is pretty much the same:

<details>
<summary>Click to see</summary>
<pre>
14:23 [carestad@laptop ~/dev/laravel/test]$ composer require genealabs/laravel-caffeine
./composer.json has been updated
Running composer update genealabs/laravel-caffeine
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - genealabs/laravel-caffeine[0.1.0, ..., 0.3.12] require illuminate/support ~5.1 -> found illuminate/support[v5.1.1, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.4.0, ..., 0.4.1] require illuminate/support 5.1.* || 5.3.* -> found illuminate/support[v5.1.1, ..., v5.3.23] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 0.4.2 requires illuminate/support 5.1.* || 5.3.* || 5.4.* -> found illuminate/support[v5.1.1, ..., v5.4.36] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 0.5.0 requires illuminate/support 5.1.* || 5.3.* || 5.4.* || 5.5.* -> found illuminate/support[v5.1.1, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.6.4, ..., 0.6.5] require illuminate/support 5.0 - 5.5 -> found illuminate/support[v5.0.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.6.0, ..., 0.6.6] require illuminate/routing 5.5.* -> found illuminate/routing[v5.5.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 0.6.7 requires illuminate/routing 5.6.* -> found illuminate/routing[v5.6.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.6.8, ..., 0.6.12] require illuminate/routing 5.3 - 5.6 -> found illuminate/routing[v5.3.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.7.0, ..., 0.7.1] require illuminate/routing 5.3 - 5.7 -> found illuminate/routing[v5.3.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[0.8.0, ..., 0.8.3] require illuminate/routing 5.3 - 5.8 -> found illuminate/routing[v5.3.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 1.0.0 requires illuminate/routing 6.0 -> found illuminate/routing[v6.0.0] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[1.0.1, ..., 1.0.5] require illuminate/routing ^6.0 -> found illuminate/routing[v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[7.0.0, ..., 7.0.2] require illuminate/routing ^7.0 -> found illuminate/routing[v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[9.0.0, ..., 9.0.4] require illuminate/routing ^9.0 -> found illuminate/routing[v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine[8.0.0, 9.0.1] require illuminate/routing ^8.0 -> found illuminate/routing[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - genealabs/laravel-caffeine 10.0.0 requires jenssegers/model dev-master@dev -> found jenssegers/model[dev-master] but it does not match your minimum-stability.
    - Root composer.json requires genealabs/laravel-caffeine * -> satisfiable by genealabs/laravel-caffeine[0.1.0, ..., 0.8.3, 1.0.0, ..., 1.0.5, 7.0.0, 7.0.1, 7.0.2, 8.0.0, 9.0.0, ..., 9.0.4, 10.0.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require genealabs/laravel-caffeine:*" to figure out if any version is installable, or "composer require genealabs/laravel-caffeine:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

</pre>
</details>

**Comment by carestad** [comment]
I tried changing that in a freshly set up application too, and it still failed to install I'm afraid. I updated my previous reply with the output of that.

**Comment by mikebronner** [comment]
@carestad could you provide a test repo that I could download? I have little time today, if you could set that up, even if it's just that failing new Laravel project, would help me be able to test this quickly. Thanks!

**Comment by DariusIII** [comment]
Actually, the issue is `jenssegers/model` package. I use my own fork of it, that is why it is working for me.

https://github.com/DariusIII/model

**Comment by carestad** [comment]
> @carestad could you provide a test repo that I could download? I have little time today, if you could set that up, even if it's just that failing new Laravel project, would help me be able to test this quickly. Thanks!

Sure! I have added everything to https://github.com/carestad/test-caffeine

Please note that there is an entry in the composer.json file there that I was using to test a fork of this repo with, but as long as you don't try to install `carestad/laravel-caffeine` it shouldn't be a problem :smile:

**Comment by mikebronner** [comment]
@carestad thanks for the test repo. I am getting the error there as well, will look into this some more.

**Pull request merged**
