### PR TITLE
Fix markdown formatting

### PR DESCRIPTION
**Pull request by Konafets**

### CODE REVIEW

**Comment by mikebronner** [comment]
That formatting was on purpose. Thanks for submitting though.

**Comment by Konafets** [comment]
Can you explain what the purpose is?

**Comment by mikebronner** [comment]
The indentation matches the indentation in the app.php file, and the committed lines should not be copied, and if copied will not cause a problem.

**Comment by Konafets** [comment]
But this destroys the whole layout of the rest of your file.
screen shot 2017-04-13 at 08 56 01

**Comment by mikebronner** [comment]
Ah, I see ... I never noticed that the markup was broke. The PR seemed like it was just a preferences-change PR. Thanks for mentioning that. Will fix.

**Pull request merged**
