### PR TITLE
Add support for Laravel 5.6

### PR DESCRIPTION
**Pull request by Jono20201**

### CODE REVIEW

**Comment by Jono20201** [comment]
Thanks!

That should only effect the testing of this package? I’m currently seeing where I am with our product and this was one of the dependencies blocking an update so wanted to get this moving 😁

**Comment by mikebronner** [comment]
Right. You should be good to go on your branch for now, I just can’t test until they come out. I don’t foresee any changes :)

**Comment by arthurkirkosa** [comment]
`laravel/browser-kit-testing` has been updated to support L5.6

**Comment by Jono20201** [comment]
I believe we are waiting for orchestra/testbench-browser-kit to update still.

I see @mikebronner has already made an issue on that repo: https://github.com/orchestral/testbench-browser-kit/issues/6

**Comment by mikebronner** [comment]
Fixed in release 0.6.7. Sorry I didn't ingest this PR, but just had to make some other tweaks as well, and it was just quicker that way. Thanks for submitting though! :)

**Comment by Jono20201** [comment]
One day I'll get my contributor badge on this repo... 😄

**Pull request closed without merging**
